# Generated by Django 2.1.1 on 2018-09-18 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_auto_20180918_0348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='assessment',
        ),
    ]
