# Generated by Django 2.1.1 on 2018-09-18 04:26

import assessments.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_auto_20180918_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionfile',
            name='zipfile',
            field=models.FileField(upload_to=assessments.models.submissionfile_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])]),
        ),
    ]
