# Generated by Django 2.1.1 on 2018-09-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_auto_20180918_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionfile',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
