#!/bin/bash

export DJANGO_SETTINGS_MODULE=turnin.settings.production
cd ~/sis
git pull
. venv/bin/activate
pip install -r requirements.txt
python project/manage.py collectstatic --noinput
python project/manage.py migrate
touch touch-to-reload
echo 'Done'
